name: BlockRewards
version: '${project.version}'
main: me.niko302.blockrewards.BlockRewards
api-version: '1.20'
commands:
  blockrewards:
    description: Main command for BlockRewards
    usage: /blockrewards <reload>
    permission: blockrewards.use