name: BlockRewards
version: '${project.version}'
main: me.niko302.blockrewards.BlockRewards
api-version: '1.20'
commands:
  blockrewards:
    description: Main command for BlockRewards
    usage: /blockrewards <reload>
    permission: blockrewards.use

permissions:
  blockrewards.use:
    description: Allows use of BlockRewards commands.
    default: true
  blockrewards.reload:
    description: Allows reloading the plugin configuration.
    default: op
  blockrewards.toggle:
    description: Allows toggling reward messages.
    default: true